language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t cro19/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true cro19/docker-react npm run test 

deploy:
  provider: elasticbeanstalk
  region: "sa-east-1"
  app: "docker-react-demo"
  env: "Dockerreactdemo-env"
  bucket_name: "elasticbeanstalk-sa-east-1-392045542429"
  bucket_path: "docker-react-demo"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY